In [147]:
import pandas as pd
import numpy as np

In [148]:
data = pd.read_excel("URINELOTS.xlsx")
data = data[['RAMJA Results','AIIMS Result culture']]
data.columns = ['RAMJA','AIIMS']
data.head()

RAMJA                  AIIMS
0                              Enterococcus faecalis  Enterococcus faecalis
1                                                NaN          Contamination
2  E.Coli, K.pneumoniae, P. aeruginosa, A. bauman...                 E.coli
3  K.pneumoniae, E. faecalis, P. mirabilis,  A. b...          CONTAMINATION
4                                                NaN                    NaN

In [149]:
TotalSamples  = data.shape[0]
TotalSamples

146

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   RAMJA   143 non-null    object
 1   AIIMS   119 non-null    object
dtypes: object(2)
memory usage: 2.4+ KB


In [172]:
ramjaNull = data.isnull().sum(axis=0)[0]
aiimsNull = data.isnull().sum(axis=0)[1]
ramjanonnull = TotalSamples - ramjaNull
aiimsnonnull = TotalSamples - aiimsNull

In [152]:
import re
def cleanup(text):
    text = str(text)
    text = text.upper()
    text = text.replace(".", " ")
    text = text.replace(" AND ", " ")
    text = re.sub(r'\s+', ' ', text)  # Use re.sub for regular expression replacement
    text = text.strip()
    return text


In [153]:
bacteriatypes = {
    "COLI" : 'Escherichia coli', 
    "PNEUMO" : 'Klebsiella pneumoniae',
    "AERUGI" : 'Pseudomonas aeruginosa',
    "BAUMAN" : 'Acinetobacter baumannii', 
    "MIRABIL" : 'Proteus mirabilis', 
    "FAECALI" : 'Enterococcus faecalis', 
    "AUREUS" : 'Staphylococcus aureus', 
    "SAPROPHY" : 'Staphylococcus saprophyticus',
    "STERI" : 'Sterile',
    "CONTA" : 'Contamination',
    "NAN" : 'NAN'
}

In [154]:
data['cleanRAMJA'] = data['RAMJA'].apply(cleanup)
data['cleanAIIMS'] = data['AIIMS'].apply(cleanup)

In [155]:
data.shape

(146, 4)

In [156]:
def check(mainstring, s1, s2):
    if (mainstring.count(s1) > 0 or mainstring.count(s2) > 0):
        #print("YES")
        return(1)
    else:
        #print("NO")
        return(0)

In [157]:
genus = ["ESCHER","KLEBS","PSEUDO","ACINE","PROT","ENTER","AURE","SAPRO","STERI","CONTA","NAN"]
species = ["COLI", "PNEUMO", "AERUGI", "BAUMAN", "MIRABIL", "FAECALI", "AUREUS", "SAPROPHY", "STERI","CONTA","NAN"]
for s1, s2 in zip(genus,species):
    data[s2] = data['cleanRAMJA'].apply(lambda x: check(x, s1, s2))

data.rename(columns=bacteriatypes, inplace=True) #change column names
# add suffix _R to column names
columns_to_modify = ['Escherichia coli','Klebsiella pneumoniae','Pseudomonas aeruginosa','Acinetobacter baumannii','Proteus mirabilis','Enterococcus faecalis','Staphylococcus aureus','Staphylococcus saprophyticus','Sterile','Contamination','NAN']
data.rename(columns={col: f"{col}_R" for col in columns_to_modify}, inplace=True)

In [158]:
genus = ["ESCHER","KLEBS","PSEUDO","ACINE","PROT","ENTER","AURE","SAPRO","STERI","CONTA","NAN"]
species = ["COLI", "PNEUMO", "AERUGI", "BAUMAN", "MIRABIL", "FAECALI", "AUREUS", "SAPROPHY", "STERI","CONTA","NAN"]
for s1, s2 in zip(genus,species):
    data[s2] = data['cleanAIIMS'].apply(lambda x: check(x, s1, s2))

data.rename(columns=bacteriatypes, inplace=True) #change column names

# add suffix _R to column names
columns_to_modify = ['Escherichia coli','Klebsiella pneumoniae','Pseudomonas aeruginosa','Acinetobacter baumannii','Proteus mirabilis','Enterococcus faecalis','Staphylococcus aureus','Staphylococcus saprophyticus','Sterile','Contamination','NAN']
data.rename(columns={col: f"{col}_A" for col in columns_to_modify}, inplace=True)

In [159]:
data.head()

RAMJA                  AIIMS  \
0                              Enterococcus faecalis  Enterococcus faecalis   
1                                                NaN          Contamination   
2  E.Coli, K.pneumoniae, P. aeruginosa, A. bauman...                 E.coli   
3  K.pneumoniae, E. faecalis, P. mirabilis,  A. b...          CONTAMINATION   
4                                                NaN                    NaN   

                                          cleanRAMJA             cleanAIIMS  \
0                              ENTEROCOCCUS FAECALIS  ENTEROCOCCUS FAECALIS   
1                                                NAN          CONTAMINATION   
2  E COLI, K PNEUMONIAE, P AERUGINOSA, A BAUMANNI...                 E COLI   
3  K PNEUMONIAE, E FAECALIS, P MIRABILIS, A BAUMA...          CONTAMINATION   
4                                                NAN                    NAN   

   Escherichia coli_R  Klebsiella pneumoniae_R  Pseudomonas aeruginosa_R  \
0                   0                        0                         0   
1                   0                        0                         0   
2                   1                        1                         1   
3                   0                        1                         0   
4                   0                        0                         0   

   Acinetobacter baumannii_R  Proteus mirabilis_R  Enterococcus faecalis_R  \
0                          0                    0                        1   
1                          0                    0                        0   
2                          1                    0                        0   
3                          1                    1                        1   
4                          0                    0                        0   

   ...  Klebsiella pneumoniae_A  Pseudomonas aeruginosa_A  \
0  ...                        0                         0   
1  ...                        0                         0   
2  ...                        0                         0   
3  ...                        0                         0   
4  ...                        0                         0   

   Acinetobacter baumannii_A  Proteus mirabilis_A  Enterococcus faecalis_A  \
0                          0                    0                        1   
1                          0                    0                        0   
2                          0                    0                        0   
3                          0                    0                        0   
4                          0                    0                        0   

   Staphylococcus aureus_A  Staphylococcus saprophyticus_A  Sterile_A  \
0                        0                               0          0   
1                        0                               0          0   
2                        0                               0          0   
3                        0                               0          0   
4                        0                               0          0   

   Contamination_A  NAN_A  
0                0      0  
1                1      0  
2                0      0  
3                1      0  
4                0      1  

[5 rows x 26 columns]

In [160]:
data.shape

(146, 26)

In [161]:
ramja = ['Escherichia coli_R','Klebsiella pneumoniae_R','Pseudomonas aeruginosa_R','Acinetobacter baumannii_R','Proteus mirabilis_R','Enterococcus faecalis_R','Staphylococcus aureus_R','Staphylococcus saprophyticus_R','Sterile_R','Contamination_R','NAN_R']
AIIMS = ['Escherichia coli_A','Klebsiella pneumoniae_R','Pseudomonas aeruginosa_R','Acinetobacter baumannii_R','Proteus mirabilis_R','Enterococcus faecalis_R','Staphylococcus aureus_R','Staphylococcus saprophyticus_R','Sterile_R','Contamination_R','NAN_R']

In [162]:
data.head()

RAMJA                  AIIMS  \
0                              Enterococcus faecalis  Enterococcus faecalis   
1                                                NaN          Contamination   
2  E.Coli, K.pneumoniae, P. aeruginosa, A. bauman...                 E.coli   
3  K.pneumoniae, E. faecalis, P. mirabilis,  A. b...          CONTAMINATION   
4                                                NaN                    NaN   

                                          cleanRAMJA             cleanAIIMS  \
0                              ENTEROCOCCUS FAECALIS  ENTEROCOCCUS FAECALIS   
1                                                NAN          CONTAMINATION   
2  E COLI, K PNEUMONIAE, P AERUGINOSA, A BAUMANNI...                 E COLI   
3  K PNEUMONIAE, E FAECALIS, P MIRABILIS, A BAUMA...          CONTAMINATION   
4                                                NAN                    NAN   

   Escherichia coli_R  Klebsiella pneumoniae_R  Pseudomonas aeruginosa_R  \
0                   0                        0                         0   
1                   0                        0                         0   
2                   1                        1                         1   
3                   0                        1                         0   
4                   0                        0                         0   

   Acinetobacter baumannii_R  Proteus mirabilis_R  Enterococcus faecalis_R  \
0                          0                    0                        1   
1                          0                    0                        0   
2                          1                    0                        0   
3                          1                    1                        1   
4                          0                    0                        0   

   ...  Klebsiella pneumoniae_A  Pseudomonas aeruginosa_A  \
0  ...                        0                         0   
1  ...                        0                         0   
2  ...                        0                         0   
3  ...                        0                         0   
4  ...                        0                         0   

   Acinetobacter baumannii_A  Proteus mirabilis_A  Enterococcus faecalis_A  \
0                          0                    0                        1   
1                          0                    0                        0   
2                          0                    0                        0   
3                          0                    0                        0   
4                          0                    0                        0   

   Staphylococcus aureus_A  Staphylococcus saprophyticus_A  Sterile_A  \
0                        0                               0          0   
1                        0                               0          0   
2                        0                               0          0   
3                        0                               0          0   
4                        0                               0          0   

   Contamination_A  NAN_A  
0                0      0  
1                1      0  
2                0      0  
3                1      0  
4                0      1  

[5 rows x 26 columns]

In [134]:
#data.to_excel("test1.xlsx")

In [168]:
from sklearn.metrics import confusion_matrix
# ramja = ['Escherichia coli_R','Klebsiella pneumoniae_R','Pseudomonas aeruginosa_R','Acinetobacter baumannii_R','Proteus mirabilis_R','Enterococcus faecalis_R','Staphylococcus aureus_R','Staphylococcus saprophyticus_R','Sterile_R']
# aiims = ['Escherichia coli_A','Klebsiella pneumoniae_A','Pseudomonas aeruginosa_A','Acinetobacter baumannii_A','Proteus mirabilis_A','Enterococcus faecalis_A','Staphylococcus aureus_A','Staphylococcus saprophyticus_A','Sterile_A']
#cm = confusion_matrix(y_test,y_pred)
# for s1, s2 in zip(aiims,ramja):
#     cm = confusion_matrix(data['Escherichia coli_A'],data['Escherichia coli_R'])

cm = confusion_matrix(data['Escherichia coli_A'],data['Escherichia coli_R'])
cm


array([[88, 40],
       [ 7, 11]], dtype=int64)

In [176]:
datanonnull = data.dropna(subset=['RAMJA','AIIMS'])

In [187]:
#datanonnull.to_excel('test2.xlsx')

In [192]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(datanonnull['Escherichia coli_A'],datanonnull['Escherichia coli_R'])
cm


array([[68, 32],
       [ 7, 11]], dtype=int64)

In [190]:
print(datanonnull['Escherichia coli_R'].value_counts())

0    75
1    43
Name: Escherichia coli_R, dtype: int64


In [210]:
contaaiims = data['Contamination_A'].value_counts()[1]

In [193]:
from sklearn.metrics import confusion_matrix

y_true = datanonnull['Escherichia coli_A']
y_pred = datanonnull['Escherichia coli_R']

cm = confusion_matrix(y_true, y_pred)
print(cm)

[[68 32]
 [ 7 11]]


In [196]:
true_positives = cm[1, 1]
actual_positives = sum(y_true == 1)
predicted_positives = sum(y_pred == 1)

print(f"True Positives: {true_positives}")
print(f"Actual Positives: {actual_positives}")
print(f"Predicted Positives: {predicted_positives}")


True Positives: 11
Actual Positives: 18
Predicted Positives: 43


In [179]:
common_nonnull = datanonnull.shape[0]

In [181]:
import pandas as pd
from sklearn.metrics import confusion_matrix

# Lists of columns for comparison
ramja = ['Escherichia coli_R','Klebsiella pneumoniae_R','Pseudomonas aeruginosa_R','Acinetobacter baumannii_R','Proteus mirabilis_R','Enterococcus faecalis_R','Staphylococcus aureus_R','Staphylococcus saprophyticus_R','Sterile_R']
aiims = ['Escherichia coli_A','Klebsiella pneumoniae_A','Pseudomonas aeruginosa_A','Acinetobacter baumannii_A','Proteus mirabilis_A','Enterococcus faecalis_A','Staphylococcus aureus_A','Staphylococcus saprophyticus_A','Sterile_A']

# List to hold each confusion matrix as a DataFrame
cm_dfs = []

# Loop through each pair of columns and compute the confusion matrix
for s1, s2 in zip(aiims, ramja):
    cm = confusion_matrix(datanonnull[s1], datanonnull[s2])
    cm_dfs.append(cm.reshape(-1,1))

# Concatenate all confusion matrix DataFrames into one
#final_cm_df = pd.concat(cm_dfs)
cm_dfs = np.hstack(cm_dfs)
# Display the final concatenated DataFrame
print(cm_dfs)


[[ 68  88 103  93  91  88  90 107  42]
 [ 32  24  13  25  26  24  27  11  12]
 [  7   4   0   0   0   3   1   0  38]
 [ 11   2   2   0   1   3   0   0  26]]


In [205]:
index = ['TN', 'FP', 'FN', 'TP']
columns = ['Escherichia coli','Klebsiella pneumoniae','Pseudomonas aeruginosa','Acinetobacter baumannii','Proteus mirabilis','Enterococcus faecalis','Staphylococcus aureus','Staphylococcus saprophyticus','Sterile']
df_cm = pd.DataFrame(cm_dfs,index,columns)
df_cm

Escherichia coli  Klebsiella pneumoniae  Pseudomonas aeruginosa  \
TN                68                     88                     103   
FP                32                     24                      13   
FN                 7                      4                       0   
TP                11                      2                       2   

    Acinetobacter baumannii  Proteus mirabilis  Enterococcus faecalis  \
TN                       93                 91                     88   
FP                       25                 26                     24   
FN                        0                  0                      3   
TP                        0                  1                      3   

    Staphylococcus aureus  Staphylococcus saprophyticus  Sterile  
TN                     90                           107       42  
FP                     27                            11       12  
FN                      1                             0       38  
TP                      0                             0       26

In [206]:
totalPositive = df_cm.loc['TP'] + df_cm.loc['FP']
totalNegative = df_cm.loc['TN'] + df_cm.loc['FN']
df_cm.loc['Total Positive'] = totalPositive
df_cm.loc['Total Negative'] = totalNegative

In [207]:
df_cm

Escherichia coli  Klebsiella pneumoniae  \
TN                            68                     88   
FP                            32                     24   
FN                             7                      4   
TP                            11                      2   
Total Positive                43                     26   
Total Negative                75                     92   

                Pseudomonas aeruginosa  Acinetobacter baumannii  \
TN                                 103                       93   
FP                                  13                       25   
FN                                   0                        0   
TP                                   2                        0   
Total Positive                      15                       25   
Total Negative                     103                       93   

                Proteus mirabilis  Enterococcus faecalis  \
TN                             91                     88   
FP                             26                     24   
FN                              0                      3   
TP                              1                      3   
Total Positive                 27                     27   
Total Negative                 91                     91   

                Staphylococcus aureus  Staphylococcus saprophyticus  Sterile  
TN                                 90                           107       42  
FP                                 27                            11       12  
FN                                  1                             0       38  
TP                                  0                             0       26  
Total Positive                     27                            11       38  
Total Negative                     91                           107       80

In [ ]:
AIIMS = [TotalSamples, aiimsNull, aiimsnonnull, common_nonnull, contaaiims]